# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Load App Store Connect API Key"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false
    )
  end

  desc "Fetch and increment build number"
  lane :fetch_and_increment_build_number do
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

  current_version = get_version_number(
    target: "PlateFinder"
  )
  latest_build_number = latest_testflight_build_number(
    api_key: api_key,
    version: current_version,
    app_identifier: app_identifier
  )
  increment_build_number(
    build_number: (latest_build_number + 1),
  )

  # Define a lane for beta testing
  lane :beta do
    match(type: "appstore") # Sync code signing certificates
    build_app              # Build the app
    upload_to_testflight   # Upload to TestFlight
  end

  # Define a lane for releasing to the App Store
  lane :release do
    match(type: "appstore")
    build_app
    upload_to_app_store    # Upload to App Store
  end
end

end
