name: iOS CI/CD - Build

on:
  push:
    branches: [develop]

env:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

jobs:
  build:
    name: Build
    runs-on: macos-15
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0.1"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Run fastlane build
        run: bundle exec fastlane development_build
